### ISSUE TITLE
API for Random Images

### ISSUE THREAD

**Issue by Man7hano** [unsplash/datasets#11]
I love your API and would like to integrate your commercial images into our product but through your API, do you consider creating an API Endpoint?

It could work the same way as your existing API, just for the usage of those datasets.

Creative Commons Images from Flickr is the same, but I like your API more. 👍

**Comment by lukechesser** [comment]
@Man7hano not sure I follow. We have an API endpoint for serving random images available here: https://unsplash.com/documentation#get-a-random-photo

**Comment by Man7hano** [comment]
Hey @lukechesser, yes I know but I am not allowed to use all of them for machine learning purposes, therefore I am not allowed to connect to the API as a partner. 
I would like to use random images within the Lite Dataset because I can use it in a commercial way through the same API.

**Comment by lukechesser** [comment]
@Man7hano ah I see what you mean. Can you not just grab a random photo from the dataset itself?

**Comment by Man7hano** [comment]
@lukechesser hmmm, I could do that but I can not load the dataset into my app it is just too big, I need to save space wherever I can. As far as I can see there is only a Python and PostgresSQL wrapper. An API is great because you only need to load a small bunch of images for every instance. I could build my own API with your dataset, but I prefer your API because it is really well set up and works great for my purposes. :) Anyway, if there is no option I will figure something out...Thanks for checking 👍

**Comment by lukechesser** [comment]
@Man7hano to be clear, the data is just a TSV. It can be loaded into anything — MySQL, SQLite, etc. The Python and Postgres documentation are just examples of how to load the TSV data into another format
