### ISSUE TITLE
Is it expected to have fields where all values are null

### ISSUE THREAD

**Issue by copiousfreetime** [unsplash/datasets#12]
When reviewing the data in the lite dataset, all of the following fields are null in all records.

* unsplash_photos.ai_primary_landmark_name
* unsplash_photos.ai_primary_landmark_latitude
* unsplash_photos.ai_primary_landmark_longitude
* unsplash_photos.ai_primary_landmark_confidence

If all of these are supposed to be null all the time - It may be useful to drop those columns from the dataset completely. 

Although if these columns do have data in the full dataset it makes sense to have them exist. If this is the case, it may be useful to update the [documentation](https://github.com/unsplash/datasets/blob/master/DOCS.md) to note that these fields are null in the lite dataset and have values in the full dataset.

In any case, just checking to make sure that this is the expected behavior.

**Comment by lukechesser** [comment]
Tagging in @TimmyCarbone

**Comment by TimmyCarbone** [comment]
This is actually a bug. Thank you for catching it, I'll take care of the fix and will bump to 1.0.1.
