### ISSUE TITLE
How large is the full dataset 

### ISSUE THREAD

**Issue by zacharywhitley** [unsplash/datasets#19]
Can you include the size of the full dataset in your README.md? It gives the size of the lite dataset at ~550Mb. I suppose I could interpolate from there but it would be nice to know what to expect while I wait to see if I'm approved for access. I'm guessing around 44Gb? Thanks.

**Comment by TimmyCarbone** [comment]
It's about 16GB. You can see some details here:
https://unsplash.com/data

We'll add a note in the Readme 👍

**Comment by vr428987** [comment]
Help me do that. I just can think and plan  But can't do the system
Including system settings I don't know how to do it. Can you call me?
Tel : +66824628997

Thank you.

ในวันที่ พฤ. 13 ส.ค. 2020 05:18 Timothy Carbone <notifications@github.com>
เขียนว่า:
