### ISSUE TITLE
Add width, height and aspect ratio of the photos

### ISSUE THREAD

**Issue by TimmyCarbone** [unsplash/datasets#21]
The dataset is missing width, height and aspect ratio of the photo.

These are 3 important elements and should be appearing as 3 distinct fields.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @TimmyCarbone , may I ask you why you think this is important? If you need the picture you will download it anyway so you will know its size

**Comment by TimmyCarbone** [comment]
Hi !

An example that comes to mind is that the dataset can also be used to extract statistics on the photography industry. This doesn't necessarily involve downloading the photo.

Also, all the metadata and data points that we have in the dataset could be extracted from the photo itself. We believe that explicitly exposing them will simplify the research phase, allowing the researcher to focus on the analysis, rather than on the data collection.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @TimmyCarbone,

Oh I see, that is a great example :) Then I hope to see these three columns soon in the dataset
