### ISSUE TITLE
Image analysis metadata available?

### ISSUE THREAD

**Issue by copiousfreetime** [unsplash/datasets#22]
Ticket #21 mentions additional image metadata that should be in the dataset. Are there other image analysis things that unsplash calculates that could be added? I'm in particular thinking of color value statistics,  mean/median pixel value, min/max pixel values etc.

**Comment by TimmyCarbone** [comment]
We do have some data around colors in the photo, coming from a 3rd party AI. We could include it in the next release, yes.
We don't do any custom image analysis yet, so we don't have data that would result from it.

I'm curious, is there any specific application you're thinking about that would use stats around pixel values for example?

**Comment by copiousfreetime** [comment]
No particular application at the moment - I was thinking of some work I did a probably a decade or more ago with CSS background / border colors on images that were derived from mean pixel color. And was thinking about mashing up the image db against a color db to allow for searching of images that were a named color distances from  of a named color or particular RGB / HSV value. Just fun experimental things to see what happens.

**Comment by lukechesser** [comment]
We have a lot of this data — we could look at exposing it in the 1.1 release 👍
