### ISSUE TITLE
cardinality and type of unsplash_photos.photos_featured

### ISSUE THREAD

**Issue by copiousfreetime** [unsplash/datasets#25]
I was checking the cardinality of various columns in the dataset and the `unsplash_photos.photos_featured` is always true. 

```text
unsplash_lite=# select photo_featured, count(*) from unsplash_photos group by 1;
 photo_featured | count
----------------+-------
 t              | 25000
```

Is this the expected value?

Also - the data type for this column in the create-tables.sql is `varchar` and I think it should be `bool`.  I did a quick reload of the data checking if it would still be valid with that change, and it would. Happy to submit a pull request for that if you like.

**Comment by TimmyCarbone** [comment]
It is expected that all the photos in the Lite dataset are featured photos.

The type being wrong is obviously an issue here. Thank you for catching this. Feel free to submit a PR and I'll approve it.
If you don't have time, I'll fix this asap, knowing that I'm currently on paternity leave so I don't have much time for coding 😄
