### ISSUE TITLE
Downloading unsplash dataset

### ISSUE THREAD

**Issue by kim-younghan** [unsplash/datasets#30]
I am trying to download unsplash dataset lite version and the link for the lite version download doesn't give me images. Is image in the download link or do I need to download it by using API?

**Comment by lukechesser** [comment]
See the [`photo_image_url` in the `photos` dataset](https://github.com/unsplash/datasets/blob/master/DOCS.md#1---photostsv)

**Comment by kim-younghan** [comment]
thanks. Now I know how to use it😃😄
