### ISSUE TITLE
Image cannot be displayed contains error

### ISSUE THREAD

**Issue by sniafas** [unsplash/datasets#31]
**Describe the bug**
Photo with id **sEDzxW4NhL4** has errors.
While it can be accessed via photo_url https://unsplash.com/photos/sEDzxW4NhL4 it cannot get accessed 
in photo_img_url https://images.unsplash.com/photo-1586019496196-bdbea65add07

**To Reproduce**
https://images.unsplash.com/photo-1586019496196-bdbea65add07

**Expected behavior**

**Additional context**

**Comment by lukechesser** [comment]
@sniafas hm, could be a stray image caching error. I'll try resetting the cache and see. As a temporary workaround (for now), if you need to access it, try appending some query parameters https://images.unsplash.com/photo-1586019496196-bdbea65add07?ixlib=rb-1.2.1&auto=format&fit=crop&w=1023&q=80
