### ISSUE TITLE
Missing photos from v1.1.0

### ISSUE THREAD

**Issue by sniafas** [unsplash/datasets#33]
**Describe the bug**
Photos.tsv numbers 24942 items. 

**Additional context**
I have detected the new photo_ids, 249 items, just in case [file](https://github.com/unsplash/datasets/files/5285130/new_images.txt)

**Comment by TimmyCarbone** [comment]
Thanks for reporting this. I'm generating a new dataset right now.

For context, we're missing some photos that were randomly selected and were too recent for all their models to be up to date, causing a usually reliable `JOIN` to delete them from the dataset.
