### ISSUE TITLE
Downloading the images

### ISSUE THREAD

**Issue by uzpaka** [unsplash/datasets#37]
Hello,

I would like to download the images using the provided urls. Do I risk getting blocked for making too many requests/downloads?

Thank you

**Comment by TimmyCarbone** [comment]
Hey @uzpaka,

No you shouldn't be blocked if you use the provided URLs to download the photos.
You can try it out and raise an issue if anything goes wrong.

Little side note: The download might fail for some deleted photos. The dataset is due for an update that is coming very soon. Between the last version's release and today, some of the photos could have been flagged or removed from Unsplash. For those, the download/request will fail.

Let us know!
