### ISSUE TITLE
Getting the updated dataset

### ISSUE THREAD

**Issue by assman** [unsplash/datasets#38]
I believe this dataset is due for an update soon, may I know if we will receive another link to download the updated version once it is out? What is the procedure to get the updated version once it is out?

**Comment by lukechesser** [comment]
@assman if you have access to the Lite dataset, the link will be updated in this repo and on unsplash.com/data.

If you have access to the Full dataset, then you'll need to re-email the team to request access to the new dataset. If you've previously been approved, it shouldn't take long to receive approval
