### ISSUE TITLE
Will I be banned if I download the pictures?

### ISSUE THREAD

**Issue by orange2008** [unsplash/datasets#44]
I've applied the full dataset and it was approved. Now I get the 47 GB dataset.
Will I be banned if I download the pictures?
I have a 1Gb/s server and I'd download the pictures in 'photos.tsv000', the url begins in 'images.unsplash.com', I wonder if I could get banned when I download them too quickly? (For a 1Gb server of mine, about 5-6 pictures per second.)

**Comment by lukechesser** [comment]
You should be okay if you're just hitting images.unsplash.com, but to prevent it, you will probably want to throttle it. We don't have any explicit mechanism in images.unsplash.com, but our CDN provider might (though I'd imagine it would have to be very sketchy looking to get it applied)
