### ISSUE TITLE
Wrong URL on some photos

### ISSUE THREAD

**Issue by peardox** [unsplash/datasets#46]
**Describe the bug**
URL is bad

**To Reproduce**
Try downloading it

**Expected behavior**
Good URL

**Additional context**

**Comment by peardox** [comment]
Closed but still broken
photo_image_url ...
https://images.unsplash.company%20by%20Alessandro%20Desantis%20-%20Downloaded%20from%20500px_jpg.jpg

**Comment by TimmyCarbone** [comment]
Sorry for the late answer. Thank you for the feedback.

This looks like an edge case. I'm adding this issue to be fixed in the next release.

**Comment by TimmyCarbone** [comment]
Just for reference, some other photos were found with issues in the Full Dataset version:

9_9hzZVjV8s https://images.unsplash.company/%20by%20Alessandro%20Desantis%20-%20Downloaded%20from%20500px_jpg.jpg
VLWy8LIdzsQ https://images.unsplash.com.jpg/
rsJtMXn3p_c https://images.unsplash.com-grass-sun.jpg/ 
D76DklsG-5U https://images.unsplash.come-home.jpg/
vigsqYux_-8 https://images.unsplash.com_thebeach.jpg/
tCICLJ5ktBE https://images.unsplash.com.jpg/
VLWy8LIdzsQ https://images.unsplash.com.jpg/
rsJtMXn3p_c https://images.unsplash.com-grass-sun.jpg/ 
D76DklsG-5U https://images.unsplash.come-home.jpg/
vigsqYux_-8 https://images.unsplash.com_thebeach.jpg/
tCICLJ5ktBE https://images.unsplash.com.jpg/

**Comment by peardox** [comment]
That looks like it tallies with my reckoning as I have 24,989 valid images out of 25,000

Will the new version have a full 25k (takes ages to download them all)

**Comment by TimmyCarbone** [comment]
This is now fixed. Fix will appear in version 1.2.1 that will be released this week.
