### ISSUE TITLE
Feature request: Add description = true feature to your random API requests

### ISSUE THREAD

**Issue by inglesuniversal** [unsplash/datasets#49]
Hello,

I'm an English Learning Educator and I have a registered project set up already.

I would like to get random images, but ONLY the ones that have a clear or detailed description field, not null or empty values.

Is there a way to do this with your current api or can it be implemented by your team as a feature request?

something like this:

https://api.unsplash.com/photos/random?description=true&description_min_chars=10&client_id=XXXXXX

params

description = true (required)

description_min_chars = int (required) minimum description characters length or char count

Regards

Hugo Barbosa

**Comment by TimmyCarbone** [comment]
Hello,

Thanks for your question and feedback.

That is unfortunately not supported by the API at the moment
I shared with the team but we don't plan to support it in a near future.

I'm closing this as it's also not really related to the datasets project.

Thank you!
