### ISSUE TITLE
Are there any similar datasets with records of anonymous user visits?

### ISSUE THREAD

**Issue by zztaki** [unsplash/datasets#54]
**Is your feature request related to a problem? Please describe.**
Unsplash is an awesome dataset with records of anonymous user visits (conversions.tsv), I wonder if there are other organizations that have open-sourced this kind of dataset with anonymous user access? It would be so cool if there was and we can add `Related Project` to link them.

**Describe the solution you'd like**
Find and then link similar datasets with records of anonymous user visits to this project.

**Describe alternatives you've considered**
No add.

**Additional context**
No add.

**Comment by lukechesser** [comment]
Thanks for the kind words @zztaki  — I'm not aware of any, but if you are, let us know
