### ISSUE TITLE
Can't download the lite data set

### ISSUE THREAD

**Issue by ashleydavis** [unsplash/datasets#57]
**Describe the bug**
Fails to download the lite data set.

**To Reproduce**
Click the link in the README: 
![unplash data download link](https://github.com/unsplash/datasets/assets/625126/ba88256c-2931-46a9-926a-c2190593af72)

**Expected behavior**
I would expect that a zip file would be downloaded. Instead I see this message in Chrome:
![Unsplash error](https://github.com/unsplash/datasets/assets/625126/6cc03f58-7dab-40ee-88f6-62f5aff2e6d8)

**Comment by JoshuaWise** [comment]
Same error here.

**Comment by vzack2001** [comment]
Same error…
curl -L "https://unsplash.com/data/lite/latest" --output "unsplash-lite.zip" --dump-header store.txt
store.txt
----
HTTP/2 302 
server: Cowboy
report-to: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1707724191&sid=c46efe9b-d3d2-4a0c-8c76-bfafa16c5add&s=%2BKmtJobuZGusv%2BeLLy30CFmSx6UXSRp3mVNQYv06WSg%3D"}]}
reporting-endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1707724191&sid=c46efe9b-d3d2-4a0c-8c76-bfafa16c5add&s=%2BKmtJobuZGusv%2BeLLy30CFmSx6UXSRp3mVNQYv06WSg%3D
nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1
referrer-policy: origin-when-cross-origin
access-control-allow-origin: unsplash.com
location: https://unsplash-datasets.s3.amazonaws.com/lite/latest/unsplash-research-dataset-lite-latest.zip
content-type: text/html; charset=utf-8
x-powered-by: hero-app
content-language: en
cache-control: no-cache
x-request-id: 5bce23eb-349c-4b61-9207-f6a3742819d6
x-runtime: 0.009806
strict-transport-security: max-age=63072000; includeSubDomains
via: 1.1 vegur, 1.1 varnish
accept-ranges: bytes
date: Mon, 12 Feb 2024 07:49:51 GMT
x-served-by: cache-iad-kiad7000074-IAD
x-cache: MISS
x-cache-hits: 0
vary: Accept, Accept-Encoding
set-cookie: require_cookie_consent=false; Expires=Tue, 11 Feb 2025 07:49:51 GMT; path=/;
set-cookie: xp-pricing=control; expires=Tue, 11 Feb 2025 07:49:51 GMT; path=/;
set-cookie: xp-content-analysis=minimal; expires=Tue, 11 Feb 2025 07:49:51 GMT; path=/;

HTTP/1.1 403 Forbidden
x-amz-request-id: 49FCZJX4Z7MCM6HC
x-amz-id-2: BFXkMKoteRylTcW5JLpV//ZrbDMD6vQTGzvjNFU2WFX9XXt6yfHrnKE4bSfwc72wj5IGMqCZwB0=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 12 Feb 2024 07:49:50 GMT
Server: AmazonS3
----
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>49FCZJX4Z7MCM6HC</RequestId><HostId>BFXkMKoteRylTcW5JLpV//ZrbDMD6vQTGzvjNFU2WFX9XXt6yfHrnKE4bSfwc72wj5IGMqCZwB0=</HostId></Error>
----

**Comment by CyberTimon** [comment]
Same issue

**Comment by TimmyCarbone** [comment]
Sorry everyone!

There was a typo in the object name. It should be fixed now.

**Comment by ashleydavis** [comment]
Thanks so much @TimmyCarbone . The link to the data is good now.

**Comment by dongdk** [comment]
i download the lite dataset, but can't find the images. how to deal with it?

**Comment by TimmyCarbone** [comment]
Hi @dongdk, the dataset doesn't contain the photos themselves. It contains links for you to download them.
