### ISSUE TITLE
no access to the full dataset

### ISSUE THREAD

**Issue by Yang-Shiqin** [unsplash/datasets#58]
got reply: "Thanks for inquiring about Unsplash Full Dataset. I would recommend you to download the Lite Dataset before using the Full one. The Lite Dataset is meant to be open and allow anyone to experiment. If you believe your experiment or research would need the whole 2M+ images, we are happy to give you access to it then.
The Full Dataset is meant for artificial intelligence and machine learning research mostly when the Lite Dataset is not sufficient enough."

**Comment by dongdk** [comment]
+1
