### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by fakerybakery** [unsplash/datasets#62]
Hi,
Just to confirm, if I train a model on the Lite dataset may I distribute it? The license says I cannot distribute the dataset, but is it correct that no restrictions are placed on models trained on the dataset?
Thanks!

**Comment by fakerybakery** [comment]
cc @TimmyCarbone

**Comment by TimmyCarbone** [comment]
I'm sorry for missing your original message.

Yes you can release and distribute models built with the Lite dataset.

Restrictions apply to the Full Dataset.

**Comment by fakerybakery** [comment]
Thanks for the clarification!

**Comment by zhiyuanyou** [comment]
Hi,

I used the Lite dataset and applied AI methods to created some new images. Could I release these new images?

I am sure these images have no competing relationship with the original ones.
