### ISSUE TITLE
Publishing on Kaggle

### ISSUE THREAD

**Issue by vopani** [unsplash/datasets#7]
Hello,

Thanks for sharing / publishing this dataset.
Are there any plans for mirroring this dataset on [Kaggle](https://www.kaggle.com/datasets)? If not, can I publish the Lite Dataset as a public dataset on Kaggle linking it back to Unsplash as the source and using the same licensing terms as here?

It would be great to make this data available on [Kaggle](https://www.kaggle.com/) where a lot of ML research and models can be built.

**Comment by lukechesser** [comment]
@vopani thanks for the suggestion. We're definitely open to sharing the lite dataset there, provided we can attach the [terms](https://github.com/unsplash/datasets/blob/master/TERMS.md).

I know of Kaggle obviously but I'm not too familiar with releasing datasets there. How does one do that lol

**Comment by vopani** [comment]
It's as easy as clicking on Create Public Dataset and uploading the files :-)
While creating you could choose a license (most of the popular ones like Creative Commons, GPL, Open Data, Community Data are available choices) or you could even link specific terms like the one mentioned in this repo as part of the description.

If you plan to publish it there, it'd be great. Else I'll be happy to publish it myself linking this repository and terms as the source and regularly keeping an eye out on updates.

**Comment by lukechesser** [comment]
Nice — I'll give that a shot and get back to you :)
